[package]
name = "infer_api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde_json.workspace = true
tokio.workspace = true
log.workspace = true
