[package]
name = "sonorust_db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sqlx.workspace = true
tokio.workspace = true
anyhow.workspace = true
serenity.workspace = true
log.workspace = true
